var Task = require('./task')
var Repo = require('./taskReposity')
let repo = new Repo()
let task1 = new Task({name:'this is a first task'})
let task2 = new Task({name:'this is a second task'})
let task3 = new Task(repo.get(1))
task1.complete()
task2.save()
task3.complete()